/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CardCategory = { 'ResearchMethods' : null } |
  { 'Theorists' : null } |
  { 'Disorders' : null } |
  { 'Studies' : null } |
  { 'Terms' : null } |
  { 'Terminology' : null } |
  { 'Cases' : null };
export type CardId = bigint;
export interface Case {
  'id' : CaseId,
  'alias' : string,
  'name' : string,
  'year' : bigint,
  'theories' : Array<TheoryId>,
  'summary' : string,
  'notoriety' : bigint,
  'category' : CrimeCategory,
  'severity' : bigint,
  'quotes' : Array<string>,
  'dsmProfile' : string,
}
export type CaseId = bigint;
export type CrimeCategory = string;
export interface Flashcard {
  'id' : CardId,
  'question' : string,
  'hint' : string,
  'answer' : string,
  'category' : CardCategory,
}
export interface JournalEntry {
  'id' : JournalEntryId,
  'title' : string,
  'caseRefs' : Array<CaseId>,
  'body' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'updatedAt' : Timestamp,
  'theoryRefs' : Array<TheoryId>,
}
export type JournalEntryId = bigint;
export interface JournalEntryInput {
  'title' : string,
  'caseRefs' : Array<CaseId>,
  'body' : string,
  'tags' : Array<string>,
  'theoryRefs' : Array<TheoryId>,
}
export interface JournalPage {
  'page' : bigint,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'entries' : Array<JournalEntry>,
}
export type Milestone = { 'Licensure' : null } |
  { 'Bachelor' : null } |
  { 'Associate' : null } |
  { 'Master' : null };
export type ReviewQuality = { 'Known' : null } |
  { 'NeedsReview' : null };
export interface SessionSummary {
  'retentionPct' : bigint,
  'totalCards' : bigint,
  'nextReviewDates' : Array<Timestamp>,
  'dueCount' : bigint,
  'cardsReviewed' : bigint,
}
export interface Theory {
  'id' : TheoryId,
  'name' : string,
  'keyTheorists' : Array<string>,
  'description' : string,
  'keywords' : Array<string>,
}
export type TheoryId = string;
export interface TheoryMatchResult {
  'explanation' : string,
  'theoryId' : TheoryId,
  'matchedCaseIds' : Array<CaseId>,
  'confidence' : bigint,
  'theoryName' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'createJournalEntry' : ActorMethod<[JournalEntryInput], JournalEntry>,
  'deleteJournalEntry' : ActorMethod<[JournalEntryId], boolean>,
  'getCase' : ActorMethod<[CaseId], [] | [Case]>,
  'getDueCards' : ActorMethod<[], Array<Flashcard>>,
  'getJournalEntry' : ActorMethod<[JournalEntryId], [] | [JournalEntry]>,
  'getJournalMilestone' : ActorMethod<[], Milestone>,
  'getSessionSummary' : ActorMethod<[], SessionSummary>,
  'getTheory' : ActorMethod<[TheoryId], [] | [Theory]>,
  'listCards' : ActorMethod<[], Array<Flashcard>>,
  'listCardsByCategory' : ActorMethod<[CardCategory], Array<Flashcard>>,
  'listCases' : ActorMethod<[], Array<Case>>,
  'listJournalEntries' : ActorMethod<[bigint, bigint], JournalPage>,
  'listTheories' : ActorMethod<[], Array<Theory>>,
  'matchTheories' : ActorMethod<[string], Array<TheoryMatchResult>>,
  'reviewCard' : ActorMethod<[CardId, ReviewQuality], undefined>,
  'searchCases' : ActorMethod<
    [[] | [string], [] | [string], [] | [bigint], [] | [bigint], [] | [bigint]],
    Array<Case>
  >,
  'searchJournalEntries' : ActorMethod<
    [[] | [Timestamp], [] | [Timestamp], [] | [string], [] | [string]],
    Array<JournalEntry>
  >,
  'updateJournalEntry' : ActorMethod<
    [JournalEntryId, JournalEntryInput],
    [] | [JournalEntry]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];