/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CaseId = IDL.Nat;
export const TheoryId = IDL.Text;
export const JournalEntryInput = IDL.Record({
  'title' : IDL.Text,
  'caseRefs' : IDL.Vec(CaseId),
  'body' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'theoryRefs' : IDL.Vec(TheoryId),
});
export const JournalEntryId = IDL.Nat;
export const Timestamp = IDL.Int;
export const JournalEntry = IDL.Record({
  'id' : JournalEntryId,
  'title' : IDL.Text,
  'caseRefs' : IDL.Vec(CaseId),
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : Timestamp,
  'theoryRefs' : IDL.Vec(TheoryId),
});
export const CrimeCategory = IDL.Text;
export const Case = IDL.Record({
  'id' : CaseId,
  'alias' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'theories' : IDL.Vec(TheoryId),
  'summary' : IDL.Text,
  'notoriety' : IDL.Nat,
  'category' : CrimeCategory,
  'severity' : IDL.Nat,
  'quotes' : IDL.Vec(IDL.Text),
  'dsmProfile' : IDL.Text,
});
export const CardId = IDL.Nat;
export const CardCategory = IDL.Variant({
  'ResearchMethods' : IDL.Null,
  'Theorists' : IDL.Null,
  'Disorders' : IDL.Null,
  'Studies' : IDL.Null,
  'Terms' : IDL.Null,
  'Terminology' : IDL.Null,
  'Cases' : IDL.Null,
});
export const Flashcard = IDL.Record({
  'id' : CardId,
  'question' : IDL.Text,
  'hint' : IDL.Text,
  'answer' : IDL.Text,
  'category' : CardCategory,
});
export const Milestone = IDL.Variant({
  'Licensure' : IDL.Null,
  'Bachelor' : IDL.Null,
  'Associate' : IDL.Null,
  'Master' : IDL.Null,
});
export const SessionSummary = IDL.Record({
  'retentionPct' : IDL.Nat,
  'totalCards' : IDL.Nat,
  'nextReviewDates' : IDL.Vec(Timestamp),
  'dueCount' : IDL.Nat,
  'cardsReviewed' : IDL.Nat,
});
export const Theory = IDL.Record({
  'id' : TheoryId,
  'name' : IDL.Text,
  'keyTheorists' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
});
export const JournalPage = IDL.Record({
  'page' : IDL.Nat,
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'entries' : IDL.Vec(JournalEntry),
});
export const TheoryMatchResult = IDL.Record({
  'explanation' : IDL.Text,
  'theoryId' : TheoryId,
  'matchedCaseIds' : IDL.Vec(CaseId),
  'confidence' : IDL.Nat,
  'theoryName' : IDL.Text,
});
export const ReviewQuality = IDL.Variant({
  'Known' : IDL.Null,
  'NeedsReview' : IDL.Null,
});

export const idlService = IDL.Service({
  'createJournalEntry' : IDL.Func([JournalEntryInput], [JournalEntry], []),
  'deleteJournalEntry' : IDL.Func([JournalEntryId], [IDL.Bool], []),
  'getCase' : IDL.Func([CaseId], [IDL.Opt(Case)], ['query']),
  'getDueCards' : IDL.Func([], [IDL.Vec(Flashcard)], []),
  'getJournalEntry' : IDL.Func(
      [JournalEntryId],
      [IDL.Opt(JournalEntry)],
      ['query'],
    ),
  'getJournalMilestone' : IDL.Func([], [Milestone], ['query']),
  'getSessionSummary' : IDL.Func([], [SessionSummary], []),
  'getTheory' : IDL.Func([TheoryId], [IDL.Opt(Theory)], ['query']),
  'listCards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
  'listCardsByCategory' : IDL.Func(
      [CardCategory],
      [IDL.Vec(Flashcard)],
      ['query'],
    ),
  'listCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'listJournalEntries' : IDL.Func([IDL.Nat, IDL.Nat], [JournalPage], ['query']),
  'listTheories' : IDL.Func([], [IDL.Vec(Theory)], ['query']),
  'matchTheories' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TheoryMatchResult)],
      ['query'],
    ),
  'reviewCard' : IDL.Func([CardId, ReviewQuality], [], []),
  'searchCases' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Case)],
      ['query'],
    ),
  'searchJournalEntries' : IDL.Func(
      [
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'updateJournalEntry' : IDL.Func(
      [JournalEntryId, JournalEntryInput],
      [IDL.Opt(JournalEntry)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CaseId = IDL.Nat;
  const TheoryId = IDL.Text;
  const JournalEntryInput = IDL.Record({
    'title' : IDL.Text,
    'caseRefs' : IDL.Vec(CaseId),
    'body' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'theoryRefs' : IDL.Vec(TheoryId),
  });
  const JournalEntryId = IDL.Nat;
  const Timestamp = IDL.Int;
  const JournalEntry = IDL.Record({
    'id' : JournalEntryId,
    'title' : IDL.Text,
    'caseRefs' : IDL.Vec(CaseId),
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : Timestamp,
    'theoryRefs' : IDL.Vec(TheoryId),
  });
  const CrimeCategory = IDL.Text;
  const Case = IDL.Record({
    'id' : CaseId,
    'alias' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'theories' : IDL.Vec(TheoryId),
    'summary' : IDL.Text,
    'notoriety' : IDL.Nat,
    'category' : CrimeCategory,
    'severity' : IDL.Nat,
    'quotes' : IDL.Vec(IDL.Text),
    'dsmProfile' : IDL.Text,
  });
  const CardId = IDL.Nat;
  const CardCategory = IDL.Variant({
    'ResearchMethods' : IDL.Null,
    'Theorists' : IDL.Null,
    'Disorders' : IDL.Null,
    'Studies' : IDL.Null,
    'Terms' : IDL.Null,
    'Terminology' : IDL.Null,
    'Cases' : IDL.Null,
  });
  const Flashcard = IDL.Record({
    'id' : CardId,
    'question' : IDL.Text,
    'hint' : IDL.Text,
    'answer' : IDL.Text,
    'category' : CardCategory,
  });
  const Milestone = IDL.Variant({
    'Licensure' : IDL.Null,
    'Bachelor' : IDL.Null,
    'Associate' : IDL.Null,
    'Master' : IDL.Null,
  });
  const SessionSummary = IDL.Record({
    'retentionPct' : IDL.Nat,
    'totalCards' : IDL.Nat,
    'nextReviewDates' : IDL.Vec(Timestamp),
    'dueCount' : IDL.Nat,
    'cardsReviewed' : IDL.Nat,
  });
  const Theory = IDL.Record({
    'id' : TheoryId,
    'name' : IDL.Text,
    'keyTheorists' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
  });
  const JournalPage = IDL.Record({
    'page' : IDL.Nat,
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'entries' : IDL.Vec(JournalEntry),
  });
  const TheoryMatchResult = IDL.Record({
    'explanation' : IDL.Text,
    'theoryId' : TheoryId,
    'matchedCaseIds' : IDL.Vec(CaseId),
    'confidence' : IDL.Nat,
    'theoryName' : IDL.Text,
  });
  const ReviewQuality = IDL.Variant({
    'Known' : IDL.Null,
    'NeedsReview' : IDL.Null,
  });
  
  return IDL.Service({
    'createJournalEntry' : IDL.Func([JournalEntryInput], [JournalEntry], []),
    'deleteJournalEntry' : IDL.Func([JournalEntryId], [IDL.Bool], []),
    'getCase' : IDL.Func([CaseId], [IDL.Opt(Case)], ['query']),
    'getDueCards' : IDL.Func([], [IDL.Vec(Flashcard)], []),
    'getJournalEntry' : IDL.Func(
        [JournalEntryId],
        [IDL.Opt(JournalEntry)],
        ['query'],
      ),
    'getJournalMilestone' : IDL.Func([], [Milestone], ['query']),
    'getSessionSummary' : IDL.Func([], [SessionSummary], []),
    'getTheory' : IDL.Func([TheoryId], [IDL.Opt(Theory)], ['query']),
    'listCards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
    'listCardsByCategory' : IDL.Func(
        [CardCategory],
        [IDL.Vec(Flashcard)],
        ['query'],
      ),
    'listCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'listJournalEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [JournalPage],
        ['query'],
      ),
    'listTheories' : IDL.Func([], [IDL.Vec(Theory)], ['query']),
    'matchTheories' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TheoryMatchResult)],
        ['query'],
      ),
    'reviewCard' : IDL.Func([CardId, ReviewQuality], [], []),
    'searchCases' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Case)],
        ['query'],
      ),
    'searchJournalEntries' : IDL.Func(
        [
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'updateJournalEntry' : IDL.Func(
        [JournalEntryId, JournalEntryInput],
        [IDL.Opt(JournalEntry)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };