/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CardId = bigint;
export type Timestamp = bigint;
export type CrimeCategory = string;
export type TheoryId = string;
export interface Theory {
    id: TheoryId;
    name: string;
    keyTheorists: Array<string>;
    description: string;
    keywords: Array<string>;
}
export type JournalEntryId = bigint;
export type CaseId = bigint;
export interface SessionSummary {
    retentionPct: bigint;
    totalCards: bigint;
    nextReviewDates: Array<Timestamp>;
    dueCount: bigint;
    cardsReviewed: bigint;
}
export interface JournalEntry {
    id: JournalEntryId;
    title: string;
    caseRefs: Array<CaseId>;
    body: string;
    createdAt: Timestamp;
    tags: Array<string>;
    updatedAt: Timestamp;
    theoryRefs: Array<TheoryId>;
}
export interface TheoryMatchResult {
    explanation: string;
    theoryId: TheoryId;
    matchedCaseIds: Array<CaseId>;
    confidence: bigint;
    theoryName: string;
}
export interface Flashcard {
    id: CardId;
    question: string;
    hint: string;
    answer: string;
    category: CardCategory;
}
export interface JournalEntryInput {
    title: string;
    caseRefs: Array<CaseId>;
    body: string;
    tags: Array<string>;
    theoryRefs: Array<TheoryId>;
}
export interface JournalPage {
    page: bigint;
    totalCount: bigint;
    pageSize: bigint;
    entries: Array<JournalEntry>;
}
export interface Case {
    id: CaseId;
    alias: string;
    name: string;
    year: bigint;
    theories: Array<TheoryId>;
    summary: string;
    notoriety: bigint;
    category: CrimeCategory;
    severity: bigint;
    quotes: Array<string>;
    dsmProfile: string;
}
export enum CardCategory {
    ResearchMethods = "ResearchMethods",
    Theorists = "Theorists",
    Disorders = "Disorders",
    Studies = "Studies",
    Terms = "Terms",
    Terminology = "Terminology",
    Cases = "Cases"
}
export enum Milestone {
    Licensure = "Licensure",
    Bachelor = "Bachelor",
    Associate = "Associate",
    Master = "Master"
}
export enum ReviewQuality {
    Known = "Known",
    NeedsReview = "NeedsReview"
}
export interface backendInterface {
    createJournalEntry(input: JournalEntryInput): Promise<JournalEntry>;
    deleteJournalEntry(id: JournalEntryId): Promise<boolean>;
    getCase(id: CaseId): Promise<Case | null>;
    getDueCards(): Promise<Array<Flashcard>>;
    getJournalEntry(id: JournalEntryId): Promise<JournalEntry | null>;
    getJournalMilestone(): Promise<Milestone>;
    getSessionSummary(): Promise<SessionSummary>;
    getTheory(id: TheoryId): Promise<Theory | null>;
    listCards(): Promise<Array<Flashcard>>;
    listCardsByCategory(category: CardCategory): Promise<Array<Flashcard>>;
    listCases(): Promise<Array<Case>>;
    listJournalEntries(page: bigint, pageSize: bigint): Promise<JournalPage>;
    listTheories(): Promise<Array<Theory>>;
    matchTheories(scenario: string): Promise<Array<TheoryMatchResult>>;
    reviewCard(cardId: CardId, quality: ReviewQuality): Promise<void>;
    searchCases(name: string | null, category: string | null, yearFrom: bigint | null, yearTo: bigint | null, minSeverity: bigint | null): Promise<Array<Case>>;
    searchJournalEntries(fromDate: Timestamp | null, toDate: Timestamp | null, tag: string | null, keyword: string | null): Promise<Array<JournalEntry>>;
    updateJournalEntry(id: JournalEntryId, input: JournalEntryInput): Promise<JournalEntry | null>;
}
import type { CardCategory as _CardCategory, CardId as _CardId, Case as _Case, Flashcard as _Flashcard, JournalEntry as _JournalEntry, Milestone as _Milestone, ReviewQuality as _ReviewQuality, Theory as _Theory, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createJournalEntry(arg0: JournalEntryInput): Promise<JournalEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJournalEntry(arg0);
            return result;
        }
    }
    async deleteJournalEntry(arg0: JournalEntryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async getCase(arg0: CaseId): Promise<Case | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCase(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCase(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDueCards(): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueCards();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueCards();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalEntry(arg0: JournalEntryId): Promise<JournalEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntry(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntry(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalMilestone(): Promise<Milestone> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalMilestone();
                return from_candid_Milestone_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalMilestone();
            return from_candid_Milestone_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionSummary(): Promise<SessionSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionSummary();
            return result;
        }
    }
    async getTheory(arg0: TheoryId): Promise<Theory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTheory(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTheory(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCards(): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCards();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCards();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCardsByCategory(arg0: CardCategory): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCardsByCategory(to_candid_CardCategory_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCardsByCategory(to_candid_CardCategory_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCases();
            return result;
        }
    }
    async listJournalEntries(arg0: bigint, arg1: bigint): Promise<JournalPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listJournalEntries(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJournalEntries(arg0, arg1);
            return result;
        }
    }
    async listTheories(): Promise<Array<Theory>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTheories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTheories();
            return result;
        }
    }
    async matchTheories(arg0: string): Promise<Array<TheoryMatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.matchTheories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.matchTheories(arg0);
            return result;
        }
    }
    async reviewCard(arg0: CardId, arg1: ReviewQuality): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewCard(arg0, to_candid_ReviewQuality_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewCard(arg0, to_candid_ReviewQuality_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async searchCases(arg0: string | null, arg1: string | null, arg2: bigint | null, arg3: bigint | null, arg4: bigint | null): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCases(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCases(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async searchJournalEntries(arg0: Timestamp | null, arg1: Timestamp | null, arg2: string | null, arg3: string | null): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJournalEntries(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJournalEntries(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateJournalEntry(arg0: JournalEntryId, arg1: JournalEntryInput): Promise<JournalEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalEntry(arg0, arg1);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalEntry(arg0, arg1);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CardCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardCategory): CardCategory {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Flashcard_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Flashcard): Flashcard {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Milestone_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Milestone): Milestone {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Case]): Case | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Theory]): Theory | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JournalEntry]): JournalEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CardId;
    question: string;
    hint: string;
    answer: string;
    category: _CardCategory;
}): {
    id: CardId;
    question: string;
    hint: string;
    answer: string;
    category: CardCategory;
} {
    return {
        id: value.id,
        question: value.question,
        hint: value.hint,
        answer: value.answer,
        category: from_candid_CardCategory_n5(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ResearchMethods: null;
} | {
    Theorists: null;
} | {
    Disorders: null;
} | {
    Studies: null;
} | {
    Terms: null;
} | {
    Terminology: null;
} | {
    Cases: null;
}): CardCategory {
    return "ResearchMethods" in value ? CardCategory.ResearchMethods : "Theorists" in value ? CardCategory.Theorists : "Disorders" in value ? CardCategory.Disorders : "Studies" in value ? CardCategory.Studies : "Terms" in value ? CardCategory.Terms : "Terminology" in value ? CardCategory.Terminology : "Cases" in value ? CardCategory.Cases : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Licensure: null;
} | {
    Bachelor: null;
} | {
    Associate: null;
} | {
    Master: null;
}): Milestone {
    return "Licensure" in value ? Milestone.Licensure : "Bachelor" in value ? Milestone.Bachelor : "Associate" in value ? Milestone.Associate : "Master" in value ? Milestone.Master : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Flashcard>): Array<Flashcard> {
    return value.map((x)=>from_candid_Flashcard_n3(_uploadFile, _downloadFile, x));
}
function to_candid_CardCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardCategory): _CardCategory {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewQuality_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewQuality): _ReviewQuality {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardCategory): {
    ResearchMethods: null;
} | {
    Theorists: null;
} | {
    Disorders: null;
} | {
    Studies: null;
} | {
    Terms: null;
} | {
    Terminology: null;
} | {
    Cases: null;
} {
    return value == CardCategory.ResearchMethods ? {
        ResearchMethods: null
    } : value == CardCategory.Theorists ? {
        Theorists: null
    } : value == CardCategory.Disorders ? {
        Disorders: null
    } : value == CardCategory.Studies ? {
        Studies: null
    } : value == CardCategory.Terms ? {
        Terms: null
    } : value == CardCategory.Terminology ? {
        Terminology: null
    } : value == CardCategory.Cases ? {
        Cases: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewQuality): {
    Known: null;
} | {
    NeedsReview: null;
} {
    return value == ReviewQuality.Known ? {
        Known: null
    } : value == ReviewQuality.NeedsReview ? {
        NeedsReview: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
